### DISCUSSION TITLE
Noob issue: Unable to configure jvb using loadBalancer

### DISCUSSION THREAD

**Discussion by sajir-dev** [jitsi-contrib/jitsi-helm#153] [Q&A]
Hi,

I am facing issue when i try to reach the jvb. 
Please help to figure out how can I set this up
Thanks in advance!

my values.yaml 

```
jvb:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-name: my-nlb
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    ports:
      - name: rtp-udp
        port: 10000
        protocol: UDP

  publicIPs:
    - 100.133.217.132
publicURL: our-url.com
```

I can see following pods running
```
jitsi-jitsi-meet-jicofo-5b87c47c87-tb7sj   1/1     Running   0          40m
jitsi-jitsi-meet-jvb-5cf57f8b4f-lln7m      1/1     Running   0          40m
jitsi-jitsi-meet-web-b64b4987c-klptc       1/1     Running   0          40m
jitsi-prosody-0                            1/1     Running   0          40m
```
And following svcs
```
NAME                       TYPE           CLUSTER-IP       EXTERNAL-IP                                                                PORT(S)                                        AGE
jitsi-jitsi-meet-jvb       LoadBalancer   172.20.253.138   jitsi-llb.amazonaws.com   10000:31018/UDP                                42m
jitsi-jitsi-meet-web       ClusterIP      172.20.147.97    <none>                                                                     80/TCP                                         42m
jitsi-prosody              ClusterIP      172.20.118.123   <none>                                                                     5280/TCP,5281/TCP,5347/TCP,5222/TCP,5269/TCP   42m

```
