### ISSUE TITLE
Request for Help: WebSocket Connection Issue with Jitsi on Azure Kubernetes

### ISSUE THREAD

**Issue by Bananenbrot1** [jitsi-contrib/jitsi-helm#112]
Hi everyone,

Firstly, I want to commend the excellent work on the Chart! It's been incredibly helpful.

I'm currently facing an issue with my Jitsi setup on an Azure Kubernetes Cluster where WebSocket support, intended for higher video quality, consistently fails. Here's the error I'm encountering:

```
BridgeChannel.js:92 WebSocket connection to 'wss://<url>/colibri-ws/10.244.8.10/a0f267fa8b539273/35fb3c8a?pwd=xxx' failed:
```

To provide some context, the Jitsi Video Bridge (JVB) is publicly available via hostport. Additionally, here’s the ingress configuration for web access:

```yaml
ingress:
    enabled: true
    ingressClassName: azure-application-gateway
    annotations:
      #kubernetes.io/ingress.class: azure/application-gateway
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: host
        paths: ["/"]
    tls:
      - secretName: jitsi-web-tls
        hosts:
          - host
```

Could anyone suggest any modifications to the ingress settings or other configuration changes that might help resolve the WebSocket connectivity issue? I'm wondering if specific adjustments are necessary for the ingress to support WebSocket connections.

Thank you for your time and any assistance you can provide!

**Comment by emrahcom** [comment]
colibri websocket is a permanent connection between the client and the server. If ingress drops the connections after a while, this will break the signaling.

You may try to increase timeouts:

```conf
ingress:
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "7200"
    nginx.ingress.kubernetes.io/proxy-sent-timeout: "7200"
```

**Comment by Bananenbrot1** [comment]
Hi emrahcom,

Thanks for the suggestion! I tried updating my configuration as you recommended, but unfortunately, it didn't resolve the issue. The error persists, and it seems like the WebSocket connection isn't being established at all. Any other ideas or adjustments I could try?

Appreciate your help!

**Comment by spijet** [comment]
Hello @Bananenbrot1!

You can try using the current `main` branch snapshot with these values:
```yaml
# jitsi-values.yaml
websockets:
  colibri:
    enabled: false
  xmpp:
    enabled: false
```

Current `main` snapshot sets all the necessary environment variables required for proper function of legacy datachannels which work well when WebSockets fail.
