### ISSUE TITLE
interface_config setting problem

### ISSUE THREAD

**Issue by robbie1-uk** [jitsi-contrib/jitsi-helm#122]
Hi,

How do we specify the custom interface_config.js values in the Helm chart?
Is there a specific section in the values.yaml file where these should be placed, and could you provide an example?

**Comment by spijet** [comment]
Hello @robbie1-uk!

This feature is already implemented in current `main`, which is set to be released as `v1.4.0` soon-ish™️. Please refer to the `values.yaml`:
https://github.com/jitsi-contrib/jitsi-helm/blob/main/values.yaml#L60-L74

**Comment by sakiphandursun** [comment]
hello @spijet 

I can't display my interface-config.js settings that I applied in values.yaml in the web interface :/ Actually, I already checked values.yaml.

**Comment by robbie1-uk** [comment]
hello @spijet

I can't display my interface-config.js settings that I applied in values.yaml in the web interface :/ Actually, I already checked values.yaml.

**Comment by spijet** [comment]
Can you post the output of `helm list -a | grep jitsi` and the contents of your `values.yaml` (preferably as a gist) here, please?

**Comment by robbie1-uk** [comment]
```
`
my-jitsi        default         1               2024-08-07 14:57:06.502124737 +0300 +03 deployed        jitsi-meet-1.3.8        stable-9111`
```
```
jvb:
  useHostPort: true
  useNodeIP: true

web:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: public
    hosts:
      - host: jitsi.mydomain.com
        paths:
          - /
    tls:
      - secretName: jitsi-tls
        hosts:
          - jitsi.mydomain.com

custom:
    contInit:
      _10_config: ""
    defaults:
      _default: ""
      _ffdhe2048_txt: ""
      _interface_config_js: "/home/k8sjitsi/_interface_config.js"
      _meet_conf: ""
      _nginx_conf: ""
      _settings_config_js: ""
      _ssl_conf: ""
      _system_config_js: ""
    configs:
      _custom_interface_config_js: ""
      _custom_config_js: ""  

```

I tried both exporting and writing my config into it, neither worked

**Comment by spijet** [comment]
You have 2 problems here:
1. At the moment, you need to use the latest `main` snapshot of the chart (e.g. as [ZIP provided by GitHub](https://github.com/jitsi-contrib/jitsi-helm/archive/refs/heads/main.zip)). Chart version `v1.3.8` doesn't have this feature.
2. In `values.yaml`, you need to specify the *contents* of your custom config file and not path to it, like this:
```yaml
web:
  custom:
    defaults:
      _interface_config_js: |
        some.variable = "lalala";
        some.other.variable = "test";
```
