### ISSUE TITLE
web docker not pulling image

### ISSUE THREAD

**Issue by sakiphandursun** [jitsi-contrib/jitsi-helm#134]
I first convert my branch to debian from the github repo, build the debian package with Dockerfile and then push it to my Docker Hub. I also put my own settings in this debian package (interface-config.js and custom-config.js)

Dockerfile:
```
FROM jitsi/web:web-1.0.8091-1
RUN apt-get update && apt-get install -y curl
COPY jitsi-meet-web_1.0.8091-1_all.deb /dir/
RUN dpkg -i /dir/jitsi-meet-web_1.0.8091-1_all.deb || apt-get install -f -y
RUN echo “Jitsi Debian Package has been installed.”
CMD [“/bin/bash”]
CMD [“tail”, “-f”, “/dev/null”]
EXPOSE 81 443
```

values.yaml:
```
global:
  # Set your cluster's DNS domain here.
  # "cluster.local" should work for most environments.
  # Set to "" to disable the use of FQDNs (default in older chart versions).
  clusterDomain: cluster.local
  podLabels: {}
  podAnnotations: {}
  releaseSecretsOverride:
    enabled: false
    # Support environment variables from pre-created secrets, such as 1Password operator
    # extraEnvFrom:
    #   - secretRef:
    #       name: '{{ include "prosody.fullname" . }}-overrides'
    #       optional: true

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

enableAuth: false
enableGuests: true
# Where Jitsi Web UI is made available
# such as jitsi.example.com
publicURL: "kmeet.customjitsi.com"

tz: Europe/Amsterdam

image:
  pullPolicy: Always

## WebSocket configuration:
#
#  Both Colibri and XMPP WebSockets are disabled by default,
#  since some LoadBalancer / Reverse Proxy setups can't pass
#  WebSocket connections properly, which might result in breakage
#  for some clients.
#
#  Enable both Colibri and XMPP WebSockets to replicate the current
#  upstream `meet.jit.si` setup. Keep both disabled to replicate
#  older setups which might be more compatible in some cases.
websockets:
  ## Colibri (JVB signalling):
  colibri:
    enabled: true
  ## XMPP (Prosody signalling):
  xmpp:
    enabled: true

web:
  replicaCount: 1
  repository: 'harbor.xxx.com/root/custom-jitsi-1'
  #repository: jitsi/web
  tag: 'latest'
```

Then I add the url of the image I built in values.yaml but it doesn't pull my custom image.

It takes the image in the image below..

<img width="255" alt="Ekran Resmi 2024-09-06 14 22 40" src="https://github.com/user-attachments/assets/20a14597-a56a-4c86-8880-db2ec222e376">

Is there a solution for this?

**Comment by spijet** [comment]
Hello @sakiphandursun!

The correct value structure for `web` pod image looks like this:
```yaml
web:
  replicaCount: 1
  image:
    repository: jitsi/web
    tag: latest
```

In your case the values are misplaced as `.Values.web.(repository|tag)`, which is incorrect.
