### ISSUE TITLE
Prosody custom config mount 

### ISSUE THREAD

**Issue by bugra-gokcek** [jitsi-contrib/jitsi-helm#135]
Hello. I want to create prosody with custom config. I created the following code for prosody mount in Values.yaml. When I browse the pod logs, I get the following output. What am I doing wrong?

```yaml
  extraVolumes:
  - name: prosody-modules-event-sync
    configMap:
      name: prosody-modules-event-sync
  - name: prosody-modules-token
    configMap:
      name: prosody-modules-token

  extraVolumeMounts:
  - name: prosody-modules-event-sync
    subPath: mod_event_sync_component.lua
    mountPath: /prosody-plugins/mod_event_sync_component.lua
  - name: prosody-modules-token
    subPath: mod_token_affiliation.lua
    mountPath: /prosody-plugins/mod_token_affiliation.lua
```
<img width="1093" alt="Screenshot 2024-09-09 at 14 10 56" src="https://github.com/user-attachments/assets/6076c764-8409-409e-9ffa-701ca660b512">
