### ISSUE TITLE
How to specify custom prosody plugin files?

### ISSUE THREAD

**Issue by anirbandas18** [jitsi-contrib/jitsi-helm#136]
Hi,

I want to use [this](https://github.com/jitsi-contrib/jitsi-helm/blob/main/README.md#adding-custom-prosody-plugins) new feature in order to specify my custom prosody plugin files as lua scripts into the prosody image during execution of `helm apply` command using this **jitsi-helm** chart.

However, I am not sure how to make my actual lua script file which is the custom prosody plugin to this **jitsi-helm** chart during `helm apply` command in order for this **jitsi-helm** chart to read the file and provide it to the underlying prosody image of this **jitsi-helm** chart.

Would you be kind enough to throw some light in to the configuration process for specifying this file from the file system to the helm chart when trying to use [this](https://github.com/jitsi-contrib/jitsi-helm/blob/main/README.md#adding-custom-prosody-plugins) feature?

**Comment by spijet** [comment]
Hello @anirbandas18!

In order to use this feature you first need to [create a ConfigMap](https://kubernetes.io/docs/reference/kubectl/generated/kubectl_create/kubectl_create_configmap/) with your plugin files inside. Then you'll need to specify the ConfigMap name and files inside it like so:
```yaml
prosody:
  extraVolumes:
    - name: prosody-modules
      configMap:
        # v Put your ConfigMap name here v #
        name: my-custom-prosody-plugins-configmap
  extraVolumeMounts:
    # Repeat this section for every plugin file...
    - name: prosody-modules
      subPath: mod_measure_client_presence.lua
      mountPath: /prosody-plugins-custom/mod_measure_client_presence.lua
    # ...or mount the whole ConfigMap like so:
    - name: prosody-modules
      mountPath: /prosody-plugins-custom
```
