### ISSUE TITLE
Can't see subtitles

### ISSUE THREAD

**Issue by SamuelePalumbo** [jitsi-contrib/jitsi-helm#144]
Hello everyone!

I'm trying to start subtitles with Jigasi on my project with no success.
In [values.yaml](https://github.com/jitsi-contrib/jitsi-helm/blob/main/values.yaml) file I set the following values:

- `Jigasi.enabled: true`
- `Jigasi.xmpp.user: jigasi`
- `Jigasi.xmpp.password: veryStrongPassword`

After that in my frontend code I've added the following option to Jitsi API:
```
transcription: {
     enabled: true,
     translationLanguages: ['en', 'es', 'de', 'fr', 'it'],
     useAppLanguage: false,
     preferredLanguage: 'it',
     autoTranscribeOnRecord: true
}
```

Now on frontend the button _Subtitles - On/Off_ is visible and the languages are the right ones. Anyway, once selected any language no subtitle is shown. The only error I can see is the following:
```
Jicofo 2024-11-05 11:22:26.898 WARNING: [337] [room=6729f1a9c2a3a647894ecd36@muc.meet.jitsi meeting_id=7183c3c1-3d8e-4c62-8b2f-b00f7dcd7b0e] TranscriberManager.selectTranscriber#201: Unable to invite transcriber due to no Jigasi instances being available
```

**Comment by fabiocody** [comment]
Hi everyone, exact same issue here

**Comment by Yerachmiel-Wand** [comment]
where in the frontend have you defined `transcription{...}`?

**Comment by SamuelePalumbo** [comment]
@Yerachmiel-Wand In an option object that I've used for instantiate the Jitsi API:

```
const option = {
     ...
     transcription: {...},
     ...
};
const api = new JitsiMeetExternalAPI(hostUrl, options);
```

**Comment by Yerachmiel-Wand** [comment]
Thanks. I didn't understand where this piece of code goes. Where is it?

**Comment by koehn** [comment]
I'm working on this right now. So far, I've figured out that to enable transcription in the Jigasi image, you need to set up your `values.yaml` to look something like this:

```
jigasi:
  image:
    tag: stable
  extraEnvs: 
    JIGASI_MODE: transcriber
    JIGASI_TRANSCRIBER_CUSTOM_SERVICE: org.jitsi.jigasi.transcription.VoskTranscriptionService
    JIGASI_TRANSCRIBER_VOSK_WEBSOCKET_URL: ws://vosk:2700
  enabled: true
  xmpp:
    user: jigasi
    password: password
```

Setting `JIGASI_MODE=transcriber` tells the Jigasi image to load the [/defaults/transcriber-sip-comminucator.properties](https://github.com/jitsi/docker-jitsi-meet/blob/26b01be8717b0c0e2513969ca230fd519cf41c2f/jigasi/rootfs/defaults/transcriber-sip-communicator.properties) file, which has hooks for the other environment variables and sets reasonable defaults. 

I'm getting another error, but at least jicofo and Jigasi are now talking to one another. I'll add more when I have it working.
