### ISSUE TITLE
Prosody pod annotations are not properly quoted

### ISSUE THREAD

**Issue by moorglade** [jitsi-contrib/jitsi-helm#167]
I try to set `podAnnotations` for Prosody in `values.yaml`:

```yaml
prosody:
  podAnnotations:
    reloader.stakater.com/auto: "true"
```

This results in an error from Helm:

```
json: cannot unmarshal bool into Go struct field ObjectMeta.spec.template.metadata.annotations of type string
```

This is because annotation values are not properly quoted in the `StatefulSet` template:
https://github.com/jitsi-contrib/jitsi-helm/blob/main/charts/prosody/templates/statefulset.yaml#L28

Compare with, for example, `jitsi-web` template, which quotes the values correctly: https://github.com/jitsi-contrib/jitsi-helm/blob/main/templates/web/deployment.yaml#L26)

As a workaround, I can quote the value twice:

```yaml
prosody:
  podAnnotations:
    reloader.stakater.com/auto: "'true'"
```
