### ISSUE TITLE
Update chart on artifacthub

### ISSUE THREAD

**Issue by drblack666** [jitsi-contrib/jitsi-helm#168]
Latest version on [artifacthub](https://artifacthub.io/packages/helm/jitsi-meet/jitsi-meet) - `1.4.1`, but as I can see in the repository chart, it was bumped to [v1.5.0](https://github.com/jitsi-contrib/jitsi-helm/commit/40ee50dc1d857ba16d462ffcc75e8c60e8f1bad1). Maybe it's worth bumping the chart to a newer version, because images were edited to [stable-10133](https://github.com/jitsi-contrib/jitsi-helm/commit/e9ce67d1bdaecc90669b609eb00d38a20b81c709) version.

**Comment by emrahcom** [comment]
FYI, it is possible to set image tags in the custom value yaml:

```
web:
  image:
    repository: jitsi/web
    tag: "stable-10184"
jicofo:
  image:
    repository: jitsi/jicofo
    tag: "stable-10184"
jvb:
  image:
    repository: jitsi/jvb
    tag: "stable-10184"
prosody:
  image:
    repository: jitsi/prosody
    tag: "stable-10184"
```
