### ISSUE TITLE
Does Jitsi-Helm currently support JWT authentication types like in docker-compose?

### ISSUE THREAD

**Issue by zr292** [jitsi-contrib/jitsi-helm#171]
I have a Rocket.Chat project and want to deploy Jitsi Meet to integrate with it. In fact, I've tried running Jitsi-meet with docker-compose and everything works well. However, this isn't the case with Helm; I can't find the authentication type to set it to JWT. I've tried customizing the jicofo, jvb, and prosody configurations, and authentication is successful, but when members join the same roomid, they cannot see each other. Do you have any solutions to resolve this issue?

**Comment by emrahcom** [comment]
I use the following values for JWT:

```
jitsi:
  jicofo:
    extraEnvs:
      ENABLE_AUTO_OWNER: "false"
      JICOFO_ENABLE_AUTH: "false"

  prosody:
    extraEnvs:
      - name: "AUTH_TYPE"
        value: "jwt"
      - name: "ENABLE_AUTH"
        value: "true"
      - name: "XMPP_MUC_MODULES"
        value: "token_affiliation"
    secretEnvs:
      JWT_APP_ID: "myappid"
      JWT_APP_SECRET: "myappsecret"
```
