### ISSUE TITLE
Prosody Pod requires manual restart after changes trigger restart of jvb/jicofo Pods

### ISSUE THREAD

**Issue by luclu** [jitsi-contrib/jitsi-helm#21]
I just started to use this helm-chart and stumbled upon the same issue https://github.com/jitsi-contrib/jitsi-helm/issues/16#issuecomment-893832532 did experience, so I thought it might be useful to seperate it into a issue of its own.

I'm using MetalLB for JVB behind NAT with Traefik for the WebUI.
Here are my values.yaml:
```yaml
publicURL: "https://meet.${SECRET_DOMAIN}"
enableAuth: false
enableGuests: true
tz: Europe/Berlin

web:
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    hosts:
    - host: "meet.${SECRET_DOMAIN}"
      paths: ['/']
    tls:
      - hosts:
          - "*.${SECRET_DOMAIN}"
          
jvb:
  UDPPort: 30378
  service:
    enabled: true
    type: LoadBalancer
    LoadbalancerIP: "${LB_JITSI_IP}"
  publicIP: "${SECRET_PUBLIC_IP}"
```

Please let me known if I can contribute more info such as logs.
