### ISSUE TITLE
How to set JVB_WS_SERVER_ID ?

### ISSUE THREAD

**Issue by publishunity** [jitsi-contrib/jitsi-helm#27]
Hello, How can I pass a value for variable JVB_WS_SERVER_ID (or JVB_WS_SERVER_ID_FALLBACK)? It has to take pod ip. Because now I see empty value between 2 slashes in a line below. There was pod ip before.

wss://dev85.local.com/colibri-ws//6e955f1068d0fb0a/5418726e?pwd=3nlu61jkso7karg95getskpepl' failed: 

In a 10-config file the line  - ` XMPP_SERVER_IP=$(dig +short ${XMPP_SERVER})` returns empty value. Then next line 
`export JVB_WS_SERVER_ID_FALLBACK=$(ip route get ${XMPP_SERVER_IP} | grep -oP '(?<=src ).*' | awk '{ print $1 '})` returns anerror in jvb logs:

[cont-init.d] 10-config: executing... 
need at least a destination address
[cont-init.d] 10-config: exited 0.
...

**Comment by spijet** [comment]
Hello @publishunity!

You can do this by setting the `.Values.jvb.extraEnvs.JVB_SERVER_ID` variable in your chart installation. The proper way to do it without modifying the chart itself is:
```yaml
# custom-values.yaml
jvb:
  extraEnvs:
    JVB_WS_SERVER_ID: <insert your jvb service name>.<namespace>.svc
web:
  extraEnvs:
    NGINX_RESOLVER: <insert your kube-dns service ip>
```

I opened a PR in #28 that adds a couple of ways to set it automatically, you can check it out.
