### ISSUE TITLE
How to enable authentication for jitsi using helm?

### ISSUE THREAD

**Issue by Abbasgori13** [jitsi-contrib/jitsi-helm#30]
I am trying to enable authentication. I saw this https://github.com/jitsi-contrib/jitsi-helm/issues/12 issue but I want to enable authentication using username and password. can you help me, please?

**Comment by sapkra** [comment]
@kpeiruza Thank you for your help. Closing it because there was no response from @Abbasgori13.

**Comment by Marker689** [comment]
So I've added an "env" section under "prosody"
```
prosody:
  enabled: true
  env:
    AUTH_TYPE: ldap
    LDAP_AUTH_METHOD: bind
    LDAP_BASE: DC=myad,DC=local
    LDAP_TLS_CHECK_PEER: "0"
    LDAP_URL: ldap://myad.local/
    LDAP_FILTER: (sAMAccountName=%u)
    LDAP_BINDDN: sys-ad@myad.local
    LDAP_VERSION: "3"
    LDAP_BINDPW: pwd
    LDAP_START_TLS: "1"
    LDAP_USE_TLS: "1"
    LDAP_TLS_CHECK_PEER: "0"
```

Also I've set this
```
enableAuth: true
enableGuests: true
```
So **LDAP auth works**, but for some reason all users need to auth, even If meet was started. Don't know how to fix it, unfortunately.
