### ISSUE TITLE
Add options to use custom prosody plugins

### ISSUE THREAD

**Issue by sapkra** [jitsi-contrib/jitsi-helm#4]
The options should add a configmap to use it as a volume on path `/prosody-plugins-custom`.

**Comment by kpeiruza** [comment]
You can simply add them by specifying extraVolumeMounts and extraVolumes in jitsi-meet.prosody.

```
resources: resources/

jitsi-meet:
  publicURL: "jitsi-metrics.kube.jitsi.cat"
  jvb:
    metrics:
      enabled: true
  jibri:
    enabled: true
  prosody:
    extraEnvFrom:
    - secretRef:
        name: '{{ include "prosody.fullname" . }}-jibri'
    extraVolumes:
    - configMap:
        name: prosody-modules
      name: prosody-modules
    extraVolumeMounts:
      subPath: jitsi-meet.cfg.lua
    - mountPath: /prosody-plugins-custom/mod_measure_client_presence.lua
      name: prosody-modules
      subPath: mod_measure_client_presence.lua
    - mountPath: /prosody-plugins-custom/mod_measure_stanza_counts.lua
      name: prosody-modules
      subPath: mod_measure_stanza_counts.lua
    - mountPath: /prosody-plugins-custom/mod_prometheus.lua
      name: prosody-modules
      subPath: mod_prometheus.lua

```
-----------------

However, you need to create a configmap containing your plugins.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: prosody-modules
binaryData:
{{- $file := printf "%s%s" .Values.resources "mod_measure_client_presence.lua" }}
  mod_measure_client_presence.lua: {{ .Files.Get $file | b64enc }}
{{- $file := printf "%s%s" .Values.resources "mod_measure_stanza_counts.lua" }}
  mod_measure_stanza_counts.lua: {{ .Files.Get $file | b64enc }}
{{- $file := printf "%s%s" .Values.resources "mod_prometheus.lua" }}
  mod_prometheus.lua: {{ .Files.Get $file | b64enc }}

```

if could make sense to add this ConfigMap to jitsi-meet/templates and make it dependent on file-existence + iterate all files, so you could simply copy your modules into resources/prosody-modules/ and get the configmap created automatically, but IMHO, mounting these files should be kept at values.yaml.

**Comment by truecorax** [comment]
Can I ask here? I've created custom config map for [event_sync](https://github.com/jitsi-contrib/prosody-plugins/tree/main/event_sync) plugin at the prosody-plugins-custom directory and added additional configuration file meet.jitsi.cfg.lua for that plugin
```
Component "event_sync.meet.jitsi" "event_sync_component"
    muc_component = "conference.meet.jitsi"
    breakout_component = "breakout.meet.jitsi"
    api_prefix = "http://your.api.server/api"

```
to the /config/conf.d. Both of them were successfully added with extra volumes
```
  extraVolumes:
    - name: prosody-event-sync-component
      configMap:
        name: prosody-event-sync-component
    - name: prosody-event-sync-config
      configMap:
        name: prosody-event-sync-config
  extraVolumeMounts:
    - name: prosody-event-sync-component
      mountPath: /prosody-plugins-custom/mod_event_sync_component.lua
      subPath: mod_event_sync_component.lua
    - name: prosody-event-sync-config
      mountPath: /config/conf.d/meet.jitsi.cfg.lua
      subPath: meet.jitsi.cfg.lua
```
but prosody failed to create certificate for domain meet.jitsi
```
chown: changing ownership of '/config/conf.d/meet.jitsi.cfg.lua': Read-only file system
chown: changing ownership of '/prosody-plugins-custom/mod_event_sync_component.lua': Read-only file system
Prosody normal mode, using default config
Generating RSA private key, 2048 bit long modulus (2 primes)
.......+++++
.......................+++++
e is 65537 (0x010001)
Choose key size (2048): Key written to /config/data/meet.jitsi.key
lua: /usr/bin/prosodyctl:635: /usr/share/lua/5.4/prosody/util/openssl.lua:109: attempt to concatenate a nil value
stack traceback:
	/usr/share/lua/5.4/prosody/util/openssl.lua:109: in method 'add_sRVName'
	/usr/share/lua/5.4/prosody/util/openssl.lua:133: in method 'from_prosody'
	/usr/share/lua/5.4/prosody/util/prosodyctl/cert.lua:46: in field 'config'
	/usr/share/lua/5.4/prosody/util/prosodyctl/cert.lua:143: in function </usr/share/lua/5.4/prosody/util/prosodyctl/cert.lua:136>
	(...tail calls...)
	/usr/bin/prosodyctl:751: in upvalue 'func'
	/usr/share/lua/5.4/prosody/util/async.lua:144: in function </usr/share/lua/5.4/prosody/util/async.lua:142>
stack traceback:
	[C]: in function 'error'
	/usr/bin/prosodyctl:635: in local 'handler'
	/usr/share/lua/5.4/prosody/util/async.lua:232: in method 'run'
	/usr/bin/prosodyctl:754: in main chunk
	[C]: in ?
Generating RSA private key, 2048 bit long modulus (2 primes)
..+++++
..........+++++
e is 65537 (0x010001)
Choose key size (2048): Key written to /config/data/auth.meet.jitsi.key
Please provide details to include in the certificate config file.
Leave the field empty to use the default value or '.' to exclude the field.
countryName (GB): localityName (The Internet): organizationName (Your Organisation): organizationalUnitName (XMPP Department): commonName (auth.meet.jitsi): emailAddress (xmpp@auth.meet.jitsi): 
Config written to /config/data/auth.meet.jitsi.cnf
Certificate written to /config/data/auth.meet.jitsi.crt
```
And I don't know what to do with that. Maybe you have any ideas that can help me. I’d appreciate it. Thanks in advance.

**Comment by emrahcom** [comment]
The issue doesn't look related with `event_sync`.

Does the error disappear if you don't add `event_sync`?

**Comment by truecorax** [comment]
without any additional configuration prosody creates certificate. even if I only add a plugin witout config file, prosody creates cerificate too. it fails if i try to add config

**Comment by spijet** [comment]
Hello @truecorax! 

Looks like you need to make sure that `readOnlyRootFilesystem` is set to `false` for the Prosody's Security Context:
```yaml
prosody:
  securityContext:
    readOnlyRootFilesystem: false
```
