### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by allanian** [jitsi-contrib/jitsi-helm#55]
Hello, can you help me with installation of jitsi
i was installed jitsi by helm with that values file
all is started, but when i go to create conference its will send me a message - you are switched off, reconnection attempt in 10s.
My cluster is under haproxy load balancer, 
10.3.3.85 - its a haproxy lb
```
 publicURL: "jitsi.sheon.com"
 global:
   ENABLE_AUTH: 0
   ENABLE_GUESTS: 1
 jvb:
   publicIP: 10.3.3.85
 web:
   ingress:
     enabled: true
     ingressClassName: "nginx"
     hosts:
     - host: jitsi.sheon.com
       paths: ['/']
```
