### ISSUE TITLE
Screen Sharing not working for 3 or more participants except everything this  everything else working fine

### ISSUE THREAD

**Issue by sunkmou** [jitsi-contrib/jitsi-helm#56]
We have used this helm chart to deploy jitsi on EKS cluster .It is working fne with audio and video with multiple participants but screen share working only for two people if third person joins meet share screen going blank and participant not able to see screen share.When I have checked in jitsi community <https://community.jitsi.org/t/solved-screen-sharing-not-working-for-3-or-more-participants/96319/10>they asked to do change in config.js file with capScreenshareBitrate: 1, but iam not able to find this here. Can you please help on this? we are stuck here.

**Comment by Nayruden** [comment]
See if this works for you https://github.com/jitsi-contrib/jitsi-helm/issues/53#issuecomment-1228709489

**Comment by sunkmou** [comment]
When I enabled websockets to TRUE, Deployment is failing with network errors.Any one who enabled web sockets can you please share sample values.yaml file here ?

**Comment by spijet** [comment]
In the end, the problem was caused by two WebSocket-related environment variables. See https://github.com/jitsi-contrib/jitsi-helm/issues/53#issuecomment-1324120219 for details.

Starting with [v1.3.0 Chart release](https://github.com/jitsi-contrib/jitsi-helm/releases/tag/v1.3.0), these variables are explicitly set to `false` unless you enable WS support for either of the components:
```yaml
# values.yaml
websockets:
  ## JVB/Colibri WS transport:
  #  (previously known as `.Values.jvb.websockets`)
  colibri:
    enabled: true
    serverID: <...>
  ## New option for Prosody/XMPP:
  xmpp:
    enabled: true
```

If you *don't* set these to `true`, however, now Jitsi Meet should work too, since now all of it's containers are aware that they shouldn't use or announce WebSocket endpoints in any way.
