### ISSUE TITLE
how can I add configuration parameters such as "channelLastN"

### ISSUE THREAD

**Issue by Freundschaft** [jitsi-contrib/jitsi-helm#72]
hi there, thanks a lot for the chart! I was wondering how I can change parameters of the config, such as "channelLastN" via the chart values directly?

**Comment by spijet** [comment]
Hello @Freundschaft!

You can control most of the Jitsi Meet options using environment variables. Check both `*-config.js` files [here](https://github.com/jitsi/docker-jitsi-meet/tree/master/web/rootfs/defaults) for the list of options you can set for the `web` pod.

If you want to add some settings that are not covered by environment variables, you can create a custom ConfigMap and mount it to the necessary pod. Init scripts and configs from the repo linked above will give you more info on how to do it.

Here's an example of how I set some custom options in one of my Jitsi Meet installations:
```yaml
## values.yaml
extraCommonEnvs:
  ENABLE_REQUIRE_DISPLAY_NAME: 'true'
  ENABLE_STEREO: 'false'
  ENABLE_OPUS_RED: 'true'
  DESKTOP_SHARING_FRAMERATE_MIN: '5'
  DESKTOP_SHARING_FRAMERATE_MAX: '20'
  ENABLE_CODEC_VP9: 'true'
  P2P_PREFERRED_CODEC: 'VP9'
  VIDEOQUALITY_PREFERRED_CODEC: 'VP9'

web:
  extraVolumes:
  - configMap:
      defaultMode: 420
      name: jitsi-meet-web-custom-config
    name: custom-config
  extraVolumeMounts:
  - mountPath: /config/custom-config.js
    subPath: custom-config.js
    name: custom-config
    readOnly: true
```

```yaml
## extra-configmap.yaml
apiVersion: v1
data:
  custom-config.js: |+
    config.pcStatsInterval = 500;
    // Make sure there's an empty line

kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: jitsi-meet
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jitsi-meet
  name: jitsi-meet-web-custom-config
  namespace: jitsi
```
