### ISSUE TITLE
How to mount file in Prosody plugins folder of Prosody pod ?

### ISSUE THREAD

**Issue by Govind10g** [jitsi-contrib/jitsi-helm#85]
Hi Team,

For Prosody Auth Matrix User Verification, we need to add below two files in prosody  plugins folder of Prosody pod.

1. mod_auth_matrix_user_verification.lua 
2. mod_matrix_power_sync.lua 
https://github.com/matrix-org/prosody-mod-auth-matrix-user-verification/tree/master#prosody-configuration-and-plugins

But I'm not able to add a volume section in envs-configmap.yaml file under charts/prosody/templates folder.
https://github.com/jitsi-contrib/jitsi-helm/blob/main/charts/prosody/templates/envs-configmap.yaml

How you help me - How can we mount these two files in prosody pod.

**Comment by Govind10g** [comment]
@spijet Can you please help me ?

**Comment by spijet** [comment]
Hello @Govind10g!

This chart includes support for custom volume mounts for Prosody, see this part in Prosody's `templates/statefulset.yaml`:
https://github.com/jitsi-contrib/jitsi-helm/blob/main/charts/prosody/templates/statefulset.yaml#L85-L101

So you can create a ConfigMap with the files you need and then refer to it in `.Values.prosody.extraVolumes` and `.Values.prosody.extraVolumeMounts`.

I gotta admit, I completely forgot to add these options to `values.yaml` and to the readme! 😅

**Comment by Govind10g** [comment]
Hello @spijet 

Under which folder I have to create a ConfigMap for prosody ??

**Comment by spijet** [comment]
No need to modify the Chart itself — you can create a new separate ConfigMap, either by writing a YAML file and feeding it to `kubectl apply`, or by using `kubectl create configmap` directly. See [Kubernetes docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/) for details.

After you've created the ConfigMap, you can reference it in Charts' values like so:
```yaml
# my-jitsi-values.yaml
prosody:
  extraVolumes:
    - name: custom-files
      configMap:
        name: my-custom-configmap # <- your CM name here
  extraVolumeMounts:
    - name: custom-files
      mountPath: /some/path/inside/prosody/pod
      readOnly: true
```
